server:
  port: 0
spring:
  application:
    name: 2st-service
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance-id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    server-url:
      defaultZone: http://localhost:8761/eureka